FROM python:3.7-slim-buster
RUN apt-get update \
    && pip install --upgrade pip

RUN mkdir mc_sim_fin
WORKDIR /mc_sim_fin

COPY requirements*.txt /mc_sim_fin/
RUN  pip install -r requirements-dev.txt

COPY . /mc_sim_fin

ENV PYTHONPATH "${PYTHONPATH}:/mc_sim_fin"
ENV CODECOV_TOKEN ${CODECOV_TOKEN}

ENTRYPOINT []
